### ISSUE TITLE
Override url

### ISSUE THREAD

**Issue by designgears** [PokeAPI/pokedex-promise-v2#13]
Would be nice to have a way to override the url without changing the code. :)

**Comment by Naramsim** [comment]
Why do you need to override the URL?
Are you using [Ditto](https://github.com/pokesource/ditto)?

**Comment by designgears** [comment]
Nope, running PokeAPI on my own server.

**Comment by Naramsim** [comment]
Ok, good feature!
Maybe we can do something like this:
```
var Pokedex = require('pokedex-promise-v2');
var P = new Pokedex({
  protocol: 'http',
  hostname: 'localhost:3000'
});
```

With default parameters set to http and pokeapi.co so one can init the Pokedex with no parameters.
Better to split hostname in hostname and port, or let them together?

What do you think @designgears @TheTommyTwitch

**Comment by TheTommyTwitch** [comment]
That sounds good. I would say keep hostname and port together in this instance.

**Comment by Naramsim** [comment]
Ok, perfect. @TheTommyTwitch, can I add webpack to our wrapper? It is a build system, you write es6 javascript and comes out a javascript compatible even with node 0.10. Can I?

**Comment by TheTommyTwitch** [comment]
Yeah 👍 on webpack.
