### ISSUE TITLE
It's useless implementation of API.

### ISSUE THREAD

**Issue by IPRIT** [PokeAPI/pokedex-promise-v2#15]
Where can I get a list of something? For ex. list of pokemons? Lists - is important part of a RESTful API.
Where is the "http://pokeapi.co/api/v2/pokemon" endpoint?

**Comment by Naramsim** [comment]
You are right. I'm developing a branch with all root endpoints.
However, I don't think at all that our wrapper is useless. :-1:  It was missing some parts of PokeAPI. Thanks for pointing it out.

**Comment by IPRIT** [comment]
@Naramsim Thank you very much for fast replies and fixes! Great!

**Comment by IPRIT** [comment]
It would be very cool if you add a few lines of texts in readme about how to use this for other people.
