### ISSUE TITLE
Will this work with a pure client app or a node backend is a must?

### ISSUE THREAD

**Issue by nitish24p** [PokeAPI/pokedex-promise-v2#25]
Can i use it in my react app directly, or a node backend is a must..

**Comment by Naramsim** [comment]
We use Webpack with `target: 'node'`. So you must run it on a server 💢 

I will try to implement a version usable in browsers.

**Comment by Naramsim** [comment]
Moreover, we use [memory-cache](https://github.com/ptarjan/node-cache) to cache calls, which works only with node.

**Comment by Naramsim** [comment]
@nitish24p several month ago we implemented https://github.com/PokeAPI/pokeapi-js-wrapper, which was what you are looking for
