### ISSUE TITLE
Support for arrays in requests

### ISSUE THREAD

**Issue by torch2424** [PokeAPI/pokedex-promise-v2#3]
Hello!

I was wondering if we could possibly request multiple pokemon in one call.

Like perhaps in a getPokemonByName call, if we pass an array of pokemon names (as strings), we could get an array as a response for the corresponding pokemon names.

The reason why I asked, is using pokeapi, I built a little battle similuator (nothing like "pokemon showdown", but something to just kill time), and it helps to call for multiple pokemon and or moves at once, to get everything at once to make response times a bit faster, and little bit less load on the backend.

This is just a suggestion, and I'd love to offer any help with this if it is decided this would be a nice feature. Just let me know what direction would be a good start. Thanks!

**Comment by TheTommyTwitch** [comment]
This is a great idea. I will look into implementing this.
