### ISSUE TITLE
8G Implementing ?

### ISSUE THREAD

**Issue by corentinmace** [PokeAPI/pokedex-promise-v2#36]
It's not really an Issue, just a question, but when do you think the 8g will be release ?

**Comment by Naramsim** [comment]
Hello @corentinmace, generation 8 will be added as soon as Veekun will release data for it. It will take a long time as it happened for the past few generations since that data is provided by the open-source community. 

I'll link you to their thread.

https://github.com/veekun/pokedex/issues/284
