### ISSUE TITLE
Nidoran is missing from the db (apparently)

### ISSUE THREAD

**Issue by GingkathFox** [PokeAPI/pokedex-promise-v2#38]
![Screen Shot 2020-04-19 at 10 23 24 AM](https://user-images.githubusercontent.com/33764485/79690314-ce9db980-8227-11ea-81bc-600fb41b6192.png)

Heres a screenshot of me attempting to search for it and not getting anything from it. Is it in the db under a special name or something?

**Comment by Kronopt** [comment]
I'm assuming you're searching for "nidoran".
You either have to search for `nidoran ♀` or `nidoran ♂`.
In the pokeapi they are [nidoran-f](https://pokeapi.co/api/v2/pokemon/nidoran-f) and [nidoran-m](https://pokeapi.co/api/v2/pokemon/nidoran-m).
Or you can search by their pokedex id: 29 and 32

**Comment by Naramsim** [comment]
Yep, and I would like to point out that we don't have any Discord bots. @GingkathFox

**Comment by GingkathFox** [comment]
@Kronopt Interesting. Discord converts ♀ to the emoji, but `-f` and `-m` work. Thanks!

@Naramsim Ik, that's my bot.
