### ISSUE TITLE
statuscode 404 on trying to get characteristics of eevee

### ISSUE THREAD

**Issue by S0LDR** [PokeAPI/pokedex-promise-v2#39]
im using pokedex-promise-v2 and when i call poke.getCharacteristicById(id), eevee's id returns a 404 while pokemon like squirtle, and pikachu work fine

**Comment by Naramsim** [comment]
Hi @S0LDR 

I think you misunderstood the endpoint. In `/characteristic/{id}` the `id` is not the `id` of a Pokemon. These `id`s range from 1 to 30: https://pokeapi.co/api/v2/characteristic/?offset=0&limit=50

The same _characteristic_ can be owned by multiple pokemon. To devise the _characteristic_ of a pokemon you should apply a formula and then with the data of all ~30 characteristics correctly place a pokemon. The formula is described here: https://bulbapedia.bulbagarden.net/wiki/Characteristic

**Comment by Naramsim** [comment]
Bumb @S0LDR
