### ISSUE TITLE
Joining the PokéAPI organisation

### ISSUE THREAD

**Issue by phalt** [PokeAPI/pokedex-promise-v2#4]
Hey! I'm the creator of the PokéAPI Service. We recently formed a [GitHub organisation](https://github.com/PokeAPI) where we can collaborate on the development and maintenance of projects surrounding the main service. We'd like to you and this project to join the organisation, where we can work together to support and maintain this project.

If you have questions, please contact me at paulandrewhallett@gmail.com

**Comment by TheTommyTwitch** [comment]
I would love to!
