### ISSUE TITLE
Object properties are kind of hidden..

### ISSUE THREAD

**Issue by YouRageQuitForMe** [PokeAPI/pokedex-promise-v2#40]
https://pastebin.com/REaHs7xR
Here's the object that comes out when I console log "eevee".. I get [object] instead of the properties.. how can I fix that?

**Comment by Naramsim** [comment]
That's an inherent Node feature, I guess.

Try giving [this](https://stackoverflow.com/a/41336822/3482533) a go, to fully log an object.
