### ISSUE TITLE
How about Typescript  support?

### ISSUE THREAD

**Issue by maykon-oliveira** [PokeAPI/pokedex-promise-v2#51]

**Comment by C-Garza** [comment]
I was actually working on making a type definition file for the [pokeapi-js-wrapper](https://github.com/PokeAPI/pokeapi-js-wrapper) as practice for some typescript I was learning lol. 

This repo has a very similar codebase, so I could work on it after if @maykon-oliveira isn't already working on it.

**Comment by HRKings** [comment]
Hey ! I've made a PR #53 that adds TS support too

**Comment by C-Garza** [comment]
> Types for pokeapi-js-wrapper should be already available somewhere.
> 
> Here: https://github.com/mudkipme/pokeapi-v2-typescript

Oh wow, that declaration file is great! They parsed the pokeapi docs and and created the interfaces straight from them. They should have uploaded it to the DefinitelyTyped repo.

**Comment by Naramsim** [comment]
@C-Garza, do you think they scraped the docs? If so we shouldn't really rely on it. Our docs are outdated and they might as well report wrong resource types.

**Comment by C-Garza** [comment]
Oh, the JSON schema would probably work really well with generating a declaration file. I'm pretty sure there's a tool that automatically does that. I'll have a look into testing that out sometime tomorrow.

**Comment by C-Garza** [comment]
> I've made a little test repo [here](https://github.com/HRKings/pokeapi-schema-typescript), the package to generate the types is a little complicate to use with the paths on the `$ref` of the schemas, but it works.

Cool, I'll fork it and play around with it. I'm thinking also maybe just scraping the docs for the descriptions they use.

**Comment by HRKings** [comment]
> > I've made a little test repo [here](https://github.com/HRKings/pokeapi-schema-typescript), the package to generate the types is a little complicate to use with the paths on the `$ref` of the schemas, but it works.
> 
> Cool, I'll fork it and play around with it. I'm thinking also maybe just scraping the docs for the descriptions they use.

Nice! I just implemented full TS support to the methods too, so its basically complete. The only thing left is to pick the schemas directly from the main repo, but there is a bug in the package that makes parsing refs correctly a pain.

It would be nice if the schemas had the description. Scraping the docs would require another pass of the `ts-morph` to add the JSDocs

**Comment by Naramsim** [comment]
Hello @maykon-oliveira, would you be so kind to test the Typescript package just created by @HRKings?

You would need to `npm i -s pokedex-promise-v2@beta`

**Comment by Naramsim** [comment]
Typescript support has been added. Thanks immensely @HRKings
